openapi: 3.0.3
servers:
  - url: http://localhost:3000/api
    description: Local dev environment
info:
  title: A Very Very Fancy Todo App's Speccccsss
  description: Duh?
  version: "1.0.0"
tags:
  - name: Users
    description: User model related endpoints `/users`
  - name: Tasks
    description: Task model related endpoints `/tasks`
  - name: Patients
    description: Patient model related endpoints `/patients`
paths: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    ResourceId:
      $ref: "./parameters/ResourceId.yaml"
    SearchText:
      $ref: "./parameters/SearchText.yaml"
  schemas:
    User:
      $ref: "./schemas/users.schemas/User.yaml"
    UsersList:
      $ref: "./schemas/users.schemas/UsersList.yaml"
    UserLoginRequest:
      $ref: "./schemas/users.schemas/UserLoginRequest.yaml"
    UserRegisterRequest:
      $ref: "./schemas/users.schemas/UserRegisterRequest.yaml"
    UserUpdateRequest:
      $ref: "./schemas/users.schemas/UserUpdateRequest.yaml"
    TaskResource:
      $ref: "./schemas/taskResource.schemas/TaskResource.yaml"
    ResourceType:
      $ref: "./schemas/taskResource.schemas/ResourceType.yaml"
    Patient:
      $ref: "./schemas/patient.schemas/Patient.yaml"
    Task:
      $ref: "./schemas/task.schemas/Task.yaml"
    TaskCreateRequest:
      $ref: "./schemas/task.schemas/TaskCreateRequest.yaml"
    TaskResponse:
      $ref: "./schemas/task.schemas/TaskResponse.yaml"
    TaskUpdateRequest:
      $ref: "./schemas/task.schemas/TaskUpdateRequest.yaml"
    DeleteResponse:
      $ref: "./schemas/DeleteResponse.yaml"
    ErrorResponse:
      $ref: "./schemas/ErrorResponse.yaml"
