openapi: 3.0.3
servers:
  - url: http://localhost:3000/api
    description: Local dev environment
info:
  title: A Very Very Fancy Todo App's Speccccsss
  description: Duh?
  version: 1.0.0
tags:
  - name: Users
    description: User model related endpoints `/users`
  - name: Tasks
    description: Task model related endpoints `/tasks`
  - name: Patients
    description: Patient model related endpoints `/patients`
paths: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    ResourceId:
      description: Resource Unique Identifier
      in: path
      name: id
      required: true
      schema:
        type: string
    SearchText:
      description: Search text
      in: query
      name: searchText
      schema:
        type: string
  schemas:
    User:
      type: object
      description: Full User model schema
      properties:
        id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
        doctorNumber:
          type: number
        createdAt:
          type: string
        updatedAt:
          type: string
    UsersList:
      type: array
      description: List of users profile
      items:
        $ref: '#/components/schemas/User'
    UserLoginRequest:
      type: object
      description: User login request payload
      properties:
        email:
          type: string
        password:
          type: string
    UserRegisterRequest:
      type: object
      description: User registration request payload
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
        specialty:
          type: string
    UserUpdateRequest:
      type: object
      description: User update request payload
      properties:
        name:
          type: string
        email:
          type: string
    TaskResource:
      type: object
      properties:
        id:
          type: string
        originalName:
          type: string
        filename:
          type: string
        mimetype:
          type: string
        size:
          type: number
        path:
          type: string
        resourceTypeId:
          type: string
        createdAt:
          type: string
          format: date-time
    Patient:
      type: object
      description: Patient model schema
      properties:
        id:
          type: string
        name:
          type: string
        phone:
          type: string
        address:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    PatientCreateRequest:
      type: object
      properties:
        name:
          type: string
        phone:
          type: string
        address:
          type: string
        doctorIds:
          type: array
          items:
            type: string
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        status:
          type: string
        deadline:
          type: string
          format: date-time
        creatorId:
          type: string
        patientId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    TaskCreateRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        deadline:
          type: string
          format: date-time
        creatorId:
          type: string
        patientId:
          type: string
          nullable: true
        assigneeIds:
          type: array
          items:
            type: string
          nullable: true
        resources:
          type: array
          items:
            type: string
            format: binary
          nullable: true
    TaskResponse:
      type: object
      description: Task object including attachments
      properties:
        assignments:
          type: array
          items:
            $ref: '#/components/schemas/User'
        patient:
          $ref: '#/components/schemas/Patient'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/TaskResource'
      allOf:
        - $ref: '#/components/schemas/Task'
    TaskUpdateRequest:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        deadline:
          type: string
          format: date-time
        creatorId:
          type: string
        patientId:
          type: string
          nullable: true
        assigneeIds:
          type: array
          items:
            type: string
          nullable: true
        resourceIdsToDelete:
          type: array
          items:
            type: string
          nullable: true
        resources:
          type: array
          items:
            type: string
            format: binary
          nullable: true
    DeleteResponse:
      type: object
      properties:
        message:
          type: string
          description: Delete message
        id:
          type: string
          description: Deleted resource id
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
        details:
          type: string
          description: Detailed error message
